import Head from 'next/head';
import Navbar from "../src/components/Navbar";
import Leaderboard from "../src/components/Leaderboard";
import Profile from "../src/components/Profile";
import PastTransactionTable from "../src/components/PastTransactionTable";
import {
  Container,
  Grid,
  GridItem
} from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "80vh" }}>
        <Navbar />
        <Container h={'100%'} maxW='container.lg'>
          <Grid
            h={'100%'}
            templateRows='repeat(2, 1fr)'
            templateColumns='repeat(2, 1fr)'
            gap={4}
          >
            <GridItem colSpan={1} bg='papayawhip' />
            <GridItem colSpan={1} bg='papayawhip' />
            <GridItem colSpan={2} bg='tomato' />
          </Grid>
        </Container>
      </main>

      <footer>
      </footer>
    </div>
  )
}
/*
width={[
  '100%', // 0-30em
  '50%', // 30em-48em
  '25%', // 48em-62em
  '15%', // 62em+
]}
*/